spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/langyilin/config-server.git
          username: langyilin
          password:
          search-paths: '/{application}/{}/{profile}'

server:
  port: 8888